apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
     app: postgre 
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "natan"
            - name: POSTGRES_PASSWORD
              value: "natan"
            - name: POSTGRES_DB
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
         containers:
           - name: web
             image: natandevback707/api:latest
             ports:
               - containerPort: 8080
             env:
              - name: POSTGRES_USER
                value: "natan"
              - name: POSTGRES_PASSWORD
                value: "natan"
              - name: POSTGRES_DB
                value: "k8s"
              - name: POSTGRES_HOST
                value: postgre