---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZmluY29kZQ==
  POSTGRES_PASSWORD: UzNjcmV0
  POSTGRES_DB: ZmluY29kZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9maW5jb25kZTpTM2NyZXRAcG9zdGdyZXM6NTQzMi9maW5jb25kZT9zY2hlbWE9cHVibGlj
  STRIPE_API_KEY: c2tfdGVzdF81MVFJQnc2MDZuUm1SVnR2c2JtaEEyaVpFam1RY1pkblpzTkZwcHdTYTAyeXdDWG9DSjZJRkM3ZmRBTTNCWWJNZjFuMFJrcU5TQVBOQXMzWVB3ZkdSVTNCNDAwTlhwM1JXbjk=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfNjcxNmIxNzJlZWRmZTAzZTcwMjI2NzVmMDRiM2FkYzEwODgxYzQyYzU3YzBjN2U1YzlmZDNjYzI0ODdjNThhNg==
  REDISCLOUD_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.0
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: natandevback707/api
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: web-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_URL
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STRIPE_API_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STRIPE_WEBHOOK_SECRET
            - name: REDISCLOUD_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDISCLOUD_URL

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
